[package]
name = "oaval/projectsaga"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
DocumentService = "anthony0br/documentservice@1.0.0"
matter = "matter-ecs/matter@0.8.4"
plasma = "matter-ecs/plasma@0.4.4"
bytenet = "ffrostflame/bytenet@0.4.5"
Bin = "red-blox/bin@^1.0.0"
Clock = "red-blox/clock@^1.0.0"
Collection = "red-blox/collection@^1.0.0"
Fetch = "red-blox/fetch@^2.0.0"
Future = "red-blox/future@^1.0.0"
Guard = "red-blox/guard@^1.0.0"
Promise = "red-blox/promise@^1.0.0"
Ratelimit = "red-blox/ratelimit@^1.0.0"
Signal = "red-blox/signal@^2.0.0"
Spawn = "red-blox/spawn@^1.0.0"